# Generated by Django 4.2.3 on 2023-07-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_body_alter_material_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='published',
        ),
        migrations.AddField(
            model_name='material',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=150, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='material',
            name='views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
