# Generated by Django 4.2.4 on 2023-08-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_sing',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
