# Generated by Django 4.2.4 on 2023-08-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
